In [1]:
# !pip install scikit-learn

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv("insurance_pre.csv")

In [4]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
 indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
y_train = np.array(y_train)
y_test = np.array(y_test)
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

In [10]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [11]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['absolute_error', 'squared_error', 'poisson', 'friedman_mse'],
'max_features': [None,'sqrt','log2'],
'n_estimators':[10,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(X_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits


C:\Users\PrakashBaskaran\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:547: FitFailedWarning: 
30 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\PrakashBaskaran\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 895, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\PrakashBaskaran\anaconda3\Lib\site-packages\sklearn\base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PrakashBaskaran\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['absolute_error', 'squared_error',
                                       'poisson', 'friedman_mse'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [12]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100}:


In [13]:
y_pred= grid.predict(X_test)

from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8724298928035553

In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.148464      0.017904         0.002881        0.001824   
1        1.329872      0.045685         0.011655        0.003362   
2        0.089887      0.008059         0.002110        0.000833   
3        0.767885      0.024902         0.008365        0.002311   
4        0.085927      0.005790         0.002093        0.000706   
5        0.813042      0.038212         0.009566        0.002208   
6        0.039547      0.004497         0.002345        0.000739   
7        0.341573      0.030644         0.010070        0.002877   
8        0.027476      0.002875         0.002500        0.000919   
9        0.254820      0.019355         0.010871        0.002058   
10       0.029861      0.003044         0.002448        0.000763   
11       0.287207      0.025786         0.012069        0.004572   
12       0.002385      0.001355         0.000000        0.000000   
13       0.001741      0.001100         0.000000        0.000000   
14       0.001986      0.000774         0.000000        0.000000   
15       0.003581      0.002304         0.000000        0.000000   
16       0.000966      0.000857         0.000000        0.000000   
17       0.001547      0.000830         0.000000        0.000000   
18       0.033176      0.001778         0.001716        0.000067   
19       0.426701      0.009157         0.012210        0.003621   
20       0.030723      0.006349         0.001736        0.000078   
21       0.335389      0.026761         0.013432        0.004278   
22       0.043691      0.005578         0.002843        0.000907   
23       0.295752      0.015990         0.007216        0.004108   

   param_criterion param_max_features param_n_estimators  \
0   absolute_error               None                 10   
1   absolute_error               None                100   
2   absolute_error               sqrt                 10   
3   absolute_error               sqrt                100   
4   absolute_error               log2                 10   
5   absolute_error               log2                100   
6    squared_error               None                 10   
7    squared_error               None                100   
8    squared_error               sqrt                 10   
9    squared_error               sqrt                100   
10   squared_error               log2                 10   
11   squared_error               log2                100   
12         poisson               None                 10   
13         poisson               None                100   
14         poisson               sqrt                 10   
15         poisson               sqrt                100   
16         poisson               log2                 10   
17         poisson               log2                100   
18    friedman_mse               None                 10   
19    friedman_mse               None                100   
20    friedman_mse               sqrt                 10   
21    friedman_mse               sqrt                100   
22    friedman_mse               log2                 10   
23    friedman_mse               log2                100   

                                               params  split0_test_score  \
0   {'criterion': 'absolute_error', 'max_features'...           0.768622   
1   {'criterion': 'absolute_error', 'max_features'...           0.783495   
2   {'criterion': 'absolute_error', 'max_features'...           0.780859   
3   {'criterion': 'absolute_error', 'max_features'...           0.802913   
4   {'criterion': 'absolute_error', 'max_features'...           0.784025   
5   {'criterion': 'absolute_error', 'max_features'...           0.803135   
6   {'criterion': 'squared_error', 'max_features':...           0.795855   
7   {'criterion': 'squared_error', 'max_features':...           0.803511   
8   {'criterion': 'squared_error', 'max_features':...           0.802192   
9   {'criterion': 'squared_error', 'max_fe

In [16]:
import pickle
filename = "finalized_GS_RF_input_preprocess.sav"
sfilename = "input_scaler_model.pkl"
sofilename = "output_scaler_model.pkl"
pickle.dump(grid, open(filename, 'wb'))

# Save the input scaler
pickle.dump(sc, open(sfilename, 'wb'))
# Save the output scaler
pickle.dump(scy, open(sofilename, 'wb'))

In [17]:
loaded_modal = pickle.load(open(filename, 'rb'))
loaded_scalar = pickle.load(open(sfilename, 'rb'))
loaded_output_scalar = pickle.load(open(sofilename, 'rb'))
preinput = loaded_scalar.transform([[32,28,1,0,1]])
preinput

C:\Users\PrakashBaskaran\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.53875174, -0.43183433, -0.0755796 , -0.98885138,  2.00280702]])

In [18]:
result = loaded_modal.predict(preinput)
result

array([0.68289256])

In [19]:
preoutput = loaded_output_scalar.inverse_transform([result])
preoutput

array([[21206.6983339]])

In [20]:
prein = sc.transform([[32,28,1,0,1]])
prein

C:\Users\PrakashBaskaran\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.53875174, -0.43183433, -0.0755796 , -0.98885138,  2.00280702]])

In [21]:
preout = scy.inverse_transform([result])
preout

array([[21206.6983339]])