In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")

In [3]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [4]:
 indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [5]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
y_train = np.array(y_train)
y_test = np.array(y_test)
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

In [8]:
scy=StandardScaler()
y_train=scy.fit_transform(y_train)
y_test=scy.transform(y_test)

In [9]:
import pickle
filename = "finalized_GS_RF_input_preprocess.sav"

In [10]:
loaded_modal = pickle.load(open(filename, 'rb'))
preinput = sc.transform([[32,28,1,0,1]])
preinput

C:\Users\PrakashBaskaran\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.53875174, -0.43183433, -0.0755796 , -0.98885138,  2.00280702]])

In [11]:
result = loaded_modal.predict(preinput)
result

array([0.67755544])

In [12]:
preoutput = scy.inverse_transform([result])
preoutput

array([[21143.6403275]])