In [1]:
import pickle
filename = "finalized_GS_RF_input_preprocess.sav"

In [2]:
import pandas as pd
import numpy as np
dataset = pd.read_csv("insurance_pre.csv")

dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

y_train = np.array(y_train)
y_test = np.array(y_test)
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

scy=StandardScaler()
y_train = scy.fit_transform(y_train)
y_test = scy.transform(y_test)

In [3]:
loaded_modal = pickle.load(open(filename, 'rb'))
preinput = sc.transform([[32,28,1,0,1]])
preinput

C:\Users\PrakashBaskaran\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.53875174, -0.43183433, -0.0755796 , -0.98885138,  2.00280702]])

In [4]:
result = loaded_modal.predict(preinput)
result

array([0.68289256])

In [5]:
preoutput = scy.inverse_transform([result])
preoutput

array([[21206.6983339]])